name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # required by gitversion
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
        
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.13
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jenkinsmasteraci:${{ env.GITVERSION_SEMVER }}
      
    - name: Push Docker Image
      run: docker push mharris867/jenkinsmasteraci:${{ env.GITVERSION_SEMVER }}
