name: Pull Request Closed

on:
  pull_request:
    types: [closed]
    
env:
  # basic  
  resourceGroup: jenkinsaci

jobs:
  build:
    name: Remove Closed PR Azure Resources
    runs-on: windows-latest
    steps:
      # checkout branch
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # required by gitversion
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
        
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.13
        
    - name: List Variables
      shell: powershell
      run: |
       Write-Host "Listing Available Environment Variables"
       get-childitem "env:"
       Write-Host "------------- End of Variable List -------------------" 
       
      # log into Azure
    - name: "Login via Azure CLI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete PR Azure Container Instance
      shell: powershell
      run: |
        az container delete -g jenkinsaci -n pull-${{ github.event.number }}-merge -y
